-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "paciente" (
	"idPaciente" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""paciente_idPaciente_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1),
	"idPessoaPaciente" bigint NOT NULL,
	"dataCadastro" timestamp with time zone NOT NULL,
	"planoDeSaude" varchar,
	"observacoes" varchar
);
--> statement-breakpoint
CREATE TABLE "pagamento" (
	"idPagamento" bigint PRIMARY KEY NOT NULL,
	"dataPagamento" date NOT NULL,
	"valor" numeric NOT NULL,
	"formaPagamento" varchar NOT NULL,
	"status" varchar NOT NULL,
	"idPagamentoConsulta" bigint NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pagamento" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "funcionario" (
	"idFuncionario" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""funcionario_idFuncionario_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1),
	"idPessoaFuncionario" bigint NOT NULL,
	"idCargoFuncionario" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pessoa" (
	"idPessoa" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""pessoa_idPessoa_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1),
	"cpfPessoa" varchar NOT NULL,
	"nomePessoa" varchar NOT NULL,
	"telefone" varchar NOT NULL,
	"email" varchar NOT NULL,
	"userId" uuid DEFAULT gen_random_uuid() NOT NULL,
	"endereco" text,
	"tipo" text,
	"ativo" boolean DEFAULT true,
	CONSTRAINT "pessoa_cpfPessoa_key" UNIQUE("cpfPessoa")
);
--> statement-breakpoint
ALTER TABLE "pessoa" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "consultaProcedimento" (
	"idConsulProc" bigint NOT NULL,
	"idProcConsul" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "consulta" (
	"idConsulta" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""consulta_idConsulta_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1),
	"dataHora" timestamp with time zone NOT NULL,
	"tipo" varchar NOT NULL,
	"status" varchar NOT NULL,
	"idPacienteConsulta" bigint NOT NULL,
	"idFuncionarioConsulta" bigint NOT NULL
);
--> statement-breakpoint
ALTER TABLE "consulta" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "procedimento" (
	"idProcedimento" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""procedimento_idProcedimento_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1),
	"nomeProcedimento" varchar NOT NULL,
	"descricao" varchar NOT NULL,
	"valor" numeric NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cargo" (
	"idCargo" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""cargo_idCargo_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1),
	"nomeCargo" varchar NOT NULL
);
--> statement-breakpoint
ALTER TABLE "cargo" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "paciente" ADD CONSTRAINT "paciente_idPessoaPaciente_fkey" FOREIGN KEY ("idPessoaPaciente") REFERENCES "public"."pessoa"("idPessoa") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "pagamento" ADD CONSTRAINT "pagamento_idPagamentoConsulta_fkey" FOREIGN KEY ("idPagamentoConsulta") REFERENCES "public"."consulta"("idConsulta") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "funcionario" ADD CONSTRAINT "funcionario_idCargoFuncionario_fkey" FOREIGN KEY ("idCargoFuncionario") REFERENCES "public"."cargo"("idCargo") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "funcionario" ADD CONSTRAINT "funcionario_idPessoaFuncionario_fkey" FOREIGN KEY ("idPessoaFuncionario") REFERENCES "public"."pessoa"("idPessoa") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "consultaProcedimento" ADD CONSTRAINT "consultaProcedimento_idConsulProc_fkey" FOREIGN KEY ("idConsulProc") REFERENCES "public"."consulta"("idConsulta") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "consultaProcedimento" ADD CONSTRAINT "consultaProcedimento_idProcConsul_fkey" FOREIGN KEY ("idProcConsul") REFERENCES "public"."procedimento"("idProcedimento") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "consulta" ADD CONSTRAINT "consulta_idFuncionarioConsulta_fkey" FOREIGN KEY ("idFuncionarioConsulta") REFERENCES "public"."funcionario"("idFuncionario") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "consulta" ADD CONSTRAINT "consulta_idPacienteConsulta_fkey" FOREIGN KEY ("idPacienteConsulta") REFERENCES "public"."paciente"("idPaciente") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE POLICY "criar pessoas" ON "pessoa" AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "editar pessoas" ON "pessoa" AS PERMISSIVE FOR UPDATE TO public;--> statement-breakpoint
CREATE POLICY "excluir pessoa" ON "pessoa" AS PERMISSIVE FOR DELETE TO public;--> statement-breakpoint
CREATE POLICY "selecionar usuarios" ON "pessoa" AS PERMISSIVE FOR SELECT TO public;--> statement-breakpoint
CREATE POLICY "Enable delete for users based on user_id" ON "consulta" AS PERMISSIVE FOR DELETE TO public USING (true);--> statement-breakpoint
CREATE POLICY "adicionar consultas" ON "consulta" AS PERMISSIVE FOR INSERT TO "authenticated";--> statement-breakpoint
CREATE POLICY "atualizar consultas" ON "consulta" AS PERMISSIVE FOR UPDATE TO "authenticated";--> statement-breakpoint
CREATE POLICY "selecionar consultas" ON "consulta" AS PERMISSIVE FOR SELECT TO public;--> statement-breakpoint
CREATE POLICY "Permitir leitura dos cargos" ON "cargo" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
*/